"""empty message

Revision ID: 255d0a3d1c15
Revises: 6030cc4a8a45
Create Date: 2018-05-04 15:33:34.444276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255d0a3d1c15'
down_revision = '6030cc4a8a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
