"""empty message

Revision ID: 64416a0b904b
Revises: 4fe663b496d3
Create Date: 2018-05-03 16:17:25.701959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64416a0b904b'
down_revision = '4fe663b496d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###
